### PR TITLE
Replaced the version of my Norwegian/Nordic list

### PR DESCRIPTION
**Pull request by DandelionSprout**
I was made aware through https://github.com/DandelionSprout/adfilt/issues/52 that pfBlockerNG still used my increasingly uBlock Origin-targeted main version of my Nordic list, which is said to have completely broke the list in pfBlockerNG after I recently removed the `[Adblock Plus 3.4]` tag from that particular list version.

I have therefore replaced that file link with that of the hosts version of my list, and am hoping that this issue is considered critical enough that it'll be fixed relatively soon.

### CODE REVIEW

**Comment by rbgarga** [comment]
@BBcan177 can you take a look at it please?

**Comment by BBcan177** [comment]
Approved

**Comment by DandelionSprout** [comment]
I've of course kept the "Allow edits from maintainers" setting turned on all along, so you guys can make whichever edits to my changes/branch that you want to.

Especially as I perform all my changes directly on GitHub through a web browser, and therefore have zero idea how to do what you just told me to do or where.

**Comment by DandelionSprout** [comment]
Nevermind my previous comment, it seems. I studied #712 to figure out which Makefile file I had to edit, so I think I've made an attempt at that just now.

**Pull request merged**
