### PR TITLE
pfSense-pkg-softflowd: support version 1.0.0

### PR DESCRIPTION
**Pull request by overhacked**
**REQUIRES** FreeBSD ports patch https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242960 to be pulled from upstream first or manually merged.

`softflowd` added support for MAC addresses in
reported flows in version 0.9.9 and additional support
for timestamping flows in earlier versions that wasn't
supported in the pfSense GUI. Lack of timestamp setting
support in the GUI meant that flow start/end timestamps
weren't being reported.

### CODE REVIEW

**Comment by jim-p** [comment]
To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://www.netgate.com/docs/pfsense/development/submitting-a-pull-request-via-github.html

Thanks!

**Comment by overhacked** [comment]
Redmine issue created: https://redmine.pfsense.org/issues/10134

**Comment by overhacked** [comment]
I pushed 222134a before I saw you had committed a `RUN_DEPENDS` change to the devel branch. Please do revert my versioned dependency if there's a reason for it to be just `>0`.

**Comment by rbgarga** [comment]
For some reason git was not able to pull from your fork so I manually merged it. Thanks!
```❯ git pull --no-ff --log --no-commit https://github.com/overhacked/freebsd-ports.git softflowd-version_1.0.0
fatal: couldn't find remote ref softflowd-version_1.0.0```

**Pull request closed without merging**
