### PR TITLE
Fixes #7039 - SSL checks with intermediate CAs

### PR DESCRIPTION
**Pull request by dractyl**
Includes the root CA in the certificate file when specifying an intermediate cert, assuming the whole chain exists in the main certificate store. If specifying a root cert directly, this should work the same as haproxy_write_certificate_crt based on the code. Tested with intermediate cert.

### CODE REVIEW

**Comment by jim-p** [comment]
Redmine: https://redmine.pfsense.org/issues/7039

**Review by jim-p — CHANGES_REQUESTED** [review]
As a part of this pull request, you must increase PORTVERSION or add a PORTREVISION line in the package Makefile. Without this version increase, the package will not be rebuilt to include the new change.

See https://docs.netgate.com/pfsense/en/latest/references/developer-style-guide.html#ports-packages-specific-rules

**Comment by dractyl** [comment]
Done.

**Review by jim-p — APPROVED** [review]

**Comment by dneuhaeuser** [comment]
unfortunately this change never found its way to the current packages, neither haproxy-stable 0.63_2 nor haproxy-devel 0.63_2 !?

**Pull request merged**
