### PR TITLE
freeradius: allow to use network prefix for clients ip

### PR DESCRIPTION
**Pull request by vktg**
Redmine Issue: https://redmine.pfsense.org/issues/9738
Ready for review

This is useful when deploying multiple APs from the same configuration

### CODE REVIEW

**Comment by vktg** [comment]
Please don't merge it - I want to change it later by creating CIDR parser for Client IP field

**Comment by vktg** [comment]
cidr/prefix parser is done

**Comment by rbgarga** [comment]
@vktg please squash commits

**Comment by vktg** [comment]
done
squashed

**Pull request merged**
