### PR TITLE
Update lcdproc_client.php bug #10320

### PR DESCRIPTION
**Pull request by kiokoman**
Bug #10320
https://redmine.pfsense.org/issues/10320

### CODE REVIEW

**Comment by kiokoman** [comment]
i not sure but do i need to increase portrevision again ? because portrevision = 2 was used by a recent merge from Renato

**Comment by jim-p** [comment]
If you rebase your fork and it no longer shows that you changed the revision, then yes, you'll need to bump it again.

**Comment by rbgarga** [comment]
@kiokoman just increase PORTREVISION again doesn't resolve the conflict.  You must rebase your branch bringing all changes from upstream to make it ready for merge

**Comment by kiokoman** [comment]
i can't find a way to rebase from the webgui, i think it's faster if i close this,  delete and reclone the project in the gui and request a new pull for only a $

**Pull request closed without merging**
