### PR TITLE
dhcp6c no release option and extra logging

### PR DESCRIPTION
**Pull request by marjohn56**
No Release and extra minimal debugging.

### CODE REVIEW

**Comment by rbgarga** [comment]
@marjohn56 ops, you committed files/ directory at repository root directory instead of net/dhcp6. Can you please re-submit?

**Comment by marjohn56** [comment]
Bugger ;-)

**Comment by rbgarga** [comment]
files/ are still there @marjohn56

**Comment by marjohn56** [comment]
Hopefully they have now gone and I've done a new PR, somedays I hate GItHub. Now at #231

**Comment by marjohn56** [comment]
Hi Renato,

 

I’ll cancel the PR’s for the  *.incs and *.php in the morning and and clean it all up as you have requested and issue a new one. I’ve issued a new on for the dhcp6c change, hopefully in the right place this time.

 

Regards,

 

Martin

**Pull request closed without merging**
