### PR TITLE
Snort binary update to version 2.9.8.3 to sync with upstream.

### PR DESCRIPTION
**Pull request by bmeeks8**
This updates the Snort binary package to version 2.9.8.3.  The previous Snort 2.9.8.0 version is now officially EOL and VRT rule updates are no longer available.

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by bmeeks8** [comment]
CLA renewal was just completed ... had not realized it was lapsed.

**Comment by cbuechler** [comment]
Thanks @bmeeks8. The original CLAs were good for 1 year, the one you just completed has no specific end date. 

Could you please re-submit this against the devel branch? I'll cherry-pick back to RELENG_2_3 as well, then once we can confirm in a 2.3.2 snapshot, I'll cherry-pick back to 2_3_1 so it's there for 2.3.1x also.

**Comment by bmeeks8** [comment]
Sure, I'll resubmit against the devel branch shortly.

**Pull request closed without merging**
