### PR TITLE
Do not list client exports for revoked certificates.

### PR DESCRIPTION
**Pull request by skrude61**
Exporting clients for revoked certificates makes no sense.

### CODE REVIEW

**Comment by jim-p** [comment]
It works fine for SSL/TLS but doesn't work for SSL/TLS + User Auth servers. For that you'll need a test on the block just above this one, for example:

```php
<?php		if (!$server['crlref'] || !is_cert_revoked($config['system']['user'][$user['uindex']]['cert'][$user['cindex']], $server['crlref'])) { ?>
servers[<?=$sindex?>][1][<?=$uindex?>] = new Array();
servers[<?=$sindex?>][1][<?=$uindex?>][0] = '<?=$user['uindex']?>';
servers[<?=$sindex?>][1][<?=$uindex?>][1] = '<?=$user['cindex']?>';
servers[<?=$sindex?>][1][<?=$uindex?>][2] = '<?=$user['name']?>';
servers[<?=$sindex?>][1][<?=$uindex?>][3] = '<?=str_replace("'", "\\'", $user['certname'])?>';
<?		}
```

**Comment by skrude61** [comment]
That's not quite true. It works for SSL/TLS + User Auth, but only for non-local user databases.
For local database your patch is not working if $config['system']['user'][$user['uindex']]['cert'][$user['cindex']] is a certref, not a cert, so I had to modify it a little bit.

**Comment by jim-p** [comment]
This looks OK now, can you also bump the version in the Makefile so the package will get rebuilt?

**Comment by skrude61** [comment]
Done.

**Comment by rbgarga** [comment]
@skreuzer can you please rebase your fork? This patch cannot be applied cleanly on current repo

**Comment by skreuzer** [comment]
> @skreuzer can you please rebase your fork? This patch cannot be applied cleanly on current repo

was this comment meant for someone else?

**Comment by rbgarga** [comment]
@skreuzer yes, sorry!

**Comment by rbgarga** [comment]
@skrude61 can you please rebase your fork? This patch cannot be applied cleanly on current repo

**Comment by skrude61** [comment]
@rbgarga Done.

**Pull request merged**
