### PR TITLE
Allow lo0/Loopback as a valid interface in OSPF/OSPF6 

### PR DESCRIPTION
**Pull request by theonemcdonald**
This allows lo0 as a valid interface in OSPF/OSPF6 for announcing loopback addresses for various reasons.

Loopback addresses can be added as IP Alias VIPs using Firewall > Virtual IPs.

Redmine Issue: https://redmine.pfsense.org/issues/11186

### CODE REVIEW

**Review by jim-p — APPROVED** [review]

**Comment by jim-p** [comment]
To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://docs.netgate.com/pfsense/en/latest/development/pull-request.html
Thanks!

**Comment by theonemcdonald** [comment]
Take a look and see if this issue is applicable here, otherwise I can create a new one.

https://redmine.pfsense.org/issues/6651

**Comment by jim-p** [comment]
That doesn't directly apply, this would be an issue under packages specifically for FRR to add this ability for OSPF/6

**Comment by theonemcdonald** [comment]
https://redmine.pfsense.org/issues/11186

**Comment by rbgarga** [comment]
Manually merged it.  Thanks!

**Pull request closed without merging**
