### PR TITLE
squid4 ssl_crtd fix

### PR DESCRIPTION
**Pull request by vktg**
Redmine Issue: https://redmine.pfsense.org/issues/9652
Ready for review

fixes sslcrtd_program program path for squid 3/4

### CODE REVIEW

**Comment by rbgarga** [comment]
@vktg please squash all commits into a single one with a meaning commit log message before we merge it

**Comment by rbgarga** [comment]
> As a part of this pull request, you must increase PORTVERSION or add a PORTREVISION line in the package Makefile. Without this version increase, the package will not be rebuilt to include the new change.
> 
> See https://www.netgate.com/docs/pfsense/development/developer-style-guide.html#ports-packages-specific-rules

@vktg if you want to keep this one as it is, I can merge it together with https://github.com/pfsense/FreeBSD-ports/pull/725 which already bumped version

**Comment by vktg** [comment]
Yes, you can merge it with https://github.com/pfsense/FreeBSD-ports/pull/725

**Comment by rbgarga** [comment]
> Yes, you can merge it with #725

Sure. Please just squash all commits into a single one with a meaning commit log message and I'll take care

**Comment by vktg** [comment]
done, squashed

**Pull request merged**
