### PR TITLE
Nut upgrade 8.0

### PR DESCRIPTION
**Pull request by dennypage**
This upgrades the NUT package for NUT 2.8.0.

Note that this depends upon nut-2.8.0_4 being pulled into the pfSense repo. It is already present in the FreeBSD repo.

### CODE REVIEW

**Comment by jim-p** [comment]
To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://docs.netgate.com/pfsense/en/latest/development/pull-request.html
Thanks!

**Comment by dennypage** [comment]
Sorry Jim.I wasn't sure that Redmine issues were being created for upstream version bumps. I will create one.

https://redmine.pfsense.org/issues/13306

**Comment by dennypage** [comment]
Can we get this merged please?

**Comment by dennypage** [comment]
Now updated for PHP 8.1

**Review by jim-p — APPROVED** [review]

**Pull request merged**
