### PR TITLE
Redmine #14299: pfBlockerNG: cURL srcint parameter missing from a few critical locations.

### PR DESCRIPTION
**Pull request by chamilton-ccn**
[Redmine #14299](https://redmine.pfsense.org/issues/14299)

### CODE REVIEW

**Comment by BBcan177** [comment]
Thanks for the patch. Seems ok to me.

**Comment by chamilton-ccn** [comment]
@BBcan177 Sure thing! Let me know if there's anything else I need to do, I'm happy to contribute.

**Comment by chamilton-ccn** [comment]
Just curious as to the status of this PR. Should I have submitted it to -devel instead? If there's anything else I can do to help, let me know. Thank you!

**Comment by chamilton-ccn** [comment]
Closing this pull request. Will open a fresh one after conflicts have been resolved.

**Pull request closed without merging**
