### PR TITLE
fix RRD summary to properly computate data volume for previous month

### PR DESCRIPTION
**Pull request by razzfazz**

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by rbgarga** [comment]
@razzfazz could you please sign the CLA? Otherwise we cannot accept patches from you. Thanks!

**Comment by razzfazz** [comment]
Done.

**Comment by jdillard** [comment]
Thanks @razzfazz! Apologies for the delay.

**Comment by doktornotor** [comment]
@rbgarga @jdillard - Can we get this to RELENG_2_3_2? Still confusing users. https://forum.pfsense.org/index.php?topic=122771.0

**Comment by gonzopancho** [comment]
it's on RELENG_2_3, so it will make it into 2.3.3, assuming we ever cut a 2.3.3-RELEASE.

We've already released 2.3.2, so it shouldn't go on RELENG_2_3_2

**Comment by doktornotor** [comment]
@gonzopancho - Hmm, I really don't see the point in not fixing buggy packages in a stable supported release.

**Comment by rbgarga** [comment]
I cherry-picked it to RELENG_2_3_2, package update will show up soon

**Pull request merged**
