### PR TITLE
Bootstrap Port NRPE

### PR DESCRIPTION
**Pull request by svenauhagen**
Hi,

this is the bootstrap port of the NRPE package.

Best
Sven

### CODE REVIEW

**Comment by djzort** [comment]
yes please pull this!

**Comment by joelsdc** [comment]
+1 for this pull !!!

**Comment by dneuhaeuser** [comment]
yes we are waiting for this package!

**Comment by jhuebner79** [comment]
Looking forward to see NRPE in pfSense again.

**Comment by xila76** [comment]
+1 too, I need NRPE back to pfsense 2.3 !

**Comment by discostur** [comment]
+1 would be nice to see NRPE back in pfsense 2.3

**Comment by cezarq** [comment]
+1 waiting for NRPE in 2.3.1

**Comment by myprs** [comment]
Would love to see NRPE reappear in 2.3! Thanks for the work in advance!

**Comment by Reivax84** [comment]
+1 to pull ;)

**Pull request merged**
