### PR TITLE
updated RADIUS logging description

### PR DESCRIPTION
**Pull request by Danilo-Z**
RADIUS Logging is enabled by default. I updated the description.

- [ ] Redmine ticket: https://redmine.pfsense.org/issues/11055
- [ ] Ready for review.

### CODE REVIEW

**Review by jim-p — CHANGES_REQUESTED** [review]
As a part of this pull request, you must increase PORTVERSION or add a PORTREVISION line in the package Makefile. Without this version increase, the package will not be rebuilt to include the new change.

See https://docs.netgate.com/pfsense/en/latest/references/developer-style-guide.html#ports-packages-specific-rules

**Comment by Danilo-Z** [comment]
Done.

**Review by rbgarga — CHANGES_REQUESTED** [review]
You added `net/pfSense-pkg-freeradius3/files/usr/local/.DS_Store` to the repository. Please remove

**Comment by Danilo-Z** [comment]
Done.

**Review by jim-p — APPROVED** [review]

**Review by rbgarga — APPROVED** [review]

**Pull request merged**
