### PR TITLE
Fix: Bug #13214 AttributeError: 'NoneType' object has no attribute 'text'

### PR DESCRIPTION
**Pull request by indgy**
This fix resolves bug [#13214](https://redmine.pfsense.org/issues/13214)

I was seeing this error on my pfsense install with ArpWatch enabled

This code checks the element exists before trying to assign the text value, if it does not exist an empty string is assigned instead.

### CODE REVIEW

**Comment by jim-p** [comment]
To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://docs.netgate.com/pfsense/en/latest/development/pull-request.html
Thanks!

**Comment by jim-p** [comment]
As a part of this pull request, you must increase PORTVERSION or add a PORTREVISION line in the package Makefile. Without this version increase, the package will not be rebuilt to include the new change.

See https://docs.netgate.com/pfsense/en/latest/references/developer-style-guide.html#ports-packages-specific-rules

**Comment by indgy** [comment]
Apologies I am not familiar with the FreeBSD port make process, I've bumped the port revision number.

There is an issue reported by portlint but it existed before my edits
FATAL: Makefile: [1]: $FreeBSD$ is deprecated in Git.

Shall I remove that line in this PR too?

**Comment by jim-p** [comment]
> There is an issue reported by portlint but it existed before my edits `FATAL: Makefile: [1]: $FreeBSD$ is deprecated in Git.`
> 
> Shall I remove that line in this PR too?

That can be left alone, no need to worry about it.

**Review by jim-p — APPROVED** [review]

**Pull request merged**
