### PR TITLE
safesearch enforcing by DNS

### PR DESCRIPTION
**Pull request by vktg**
Redmine Issue: https://redmine.pfsense.org/issues/9874
 Ready for review

Add ability to force DNS redirection to safesearch versions of Google, Yandex, DuckDuckGo, Bing and Pixabay
See details on redmine

### CODE REVIEW

**Comment by rbgarga** [comment]
@BBcan177 please review this change

**Comment by BBcan177** [comment]
> @BBcan177 please review this change

I sent @vktg a message about not restarting Unbound after saving these settings as that can cause some unexpected behavior. Best to only save the settings, and let the "Force Update/Reload" enable/disable these changes. I also sent some recommended guidelines on how to fix the code to address this.

**Comment by vktg** [comment]
got it,
in process

**Comment by rbgarga** [comment]
@BBcan177 can you review again please?

**Comment by BBcan177** [comment]
Testing it out. 

There might be an issue with duplicate domains... So if one of these safesearch redirection domains is added at the same time the domain is already in a DNSBL Blocklist might cause Unbound to not start. This might only be the case when TLD is enabled...

**Comment by rbgarga** [comment]
Any news about it @BBcan177 ?

**Comment by vktg** [comment]
> Any news about it @BBcan177 ?

PR is not completed to submit it to @BBcan177

**Comment by vktg** [comment]
whitelist code added,
@BBcan177  please check it

**Comment by vktg** [comment]
see new PR https://github.com/pfsense/FreeBSD-ports/pull/754

**Pull request closed without merging**
