### PR TITLE
escape % in squid help text method

### PR DESCRIPTION
**Pull request by kcrawley**
fixes regression in pfSense haproxy package

### CODE REVIEW

**Comment by kcrawley** [comment]
https://redmine.pfsense.org/issues/7232

**Comment by kcrawley** [comment]
LA signed

**Comment by rbgarga** [comment]
@kcrawley Please bump PORTVERSION or PORTREVISION on pfSense-pkg-haproxy/Makefile.

Also, did you check if pfSense-pkg-haproxy-devel have the same problem?

cc: @PiBa-NL

**Comment by rbgarga** [comment]
Manually committed, thanks!

**Comment by kcrawley** [comment]
@rbgarga did not fix in `devel`, was not aware of that package. a little covered up at the moment, but I'll look at it in the next 24 hrs.

**Pull request closed without merging**
