### PR TITLE
Squid LDAP auth fix. Issue #10379

### PR DESCRIPTION
**Pull request by vktg**
Redmine Issue: https://redmine.pfsense.org/issues/10379
Ready for review

> pfsense 2.4.4p3 with all packages updated, using squid with LDAP authentication was working perfectly, server with 2 years or more of smooth operation in previous updates, after upgrading to 2.4.5 both LDAP and RADIUS permanently apply for authentication even using valid credentials. Diagnostic/authentication testing successfully validates users. Only the Squid that is not working properly.

Changes in PR https://github.com/pfsense/FreeBSD-ports/pull/729 create an invalid configuration string:
auth_param basic program /usr/local/libexec/squid/basic_ldap_auth -v 3 -b 'CN=Users,DC=test,DC=int' -D 'CN=Administrator,CN=Users,DC=test,DC=int' **'-w 123'** -f 'sAMAccountName=%s' -u 'cn' -P '192.168.1.10:389'

This PR fix it to:
'CN=Users,DC=test,DC=int' -D 'CN=Administrator,CN=Users,DC=test,DC=int' **-w '123'** -f 'sAMAccountName=%s' -u 'cn' -P '192.168.1.10:389'
and adds '-R do not follow referrals' option to WebGUI

### CODE REVIEW

**Comment by ismael-azambuja** [comment]
Hi, i change this fix, but dont work here...
0.4.44_8 OK : auth_param basic program /usr/local/libexec/squid/basic_ldap_auth -v 3 -b DC=UERGS,DC=RS -D CN=SQUID,OU=ADMINS,DC=UERGS,DC=RS -w password -f "sAMAccountName=%s" -u uid -P 10.34.0.16:389

0.4.44_15 Problem, I tried and it did not work here:

auth_param basic program /usr/local/libexec/squid/basic_ldap_auth -v 3 -b 'DC=UERGS,DC=RS' -D 'CN=SQUID,OU=ADMINS,DC=UERGS,DC=RS' '-w password' -f 'sAMAccountName=%s' -u 'uid' -P '172.16.0.16:389'

auth_param basic program /usr/local/libexec/squid/basic_ldap_auth -v 3 -b 'DC=UERGS,DC=RS' -D 'CN=SQUID,OU=ADMINS,DC=UERGS,DC=RS' -w 'password' -f 'sAMAccountName=%s' -u 'uid' -P '172.16.0.16:389'

auth_param basic program /usr/local/libexec/squid/basic_ldap_auth -v 3 -b DC=UERGS,DC=RS -D CN=SQUID,OU=ADMINS,DC=UERGS,DC=RS -w password -f sAMAccountName=%s -u uid -P 172.16.0.16:389

**Comment by o71** [comment]
Hello,
I tested but there are 2 problems with the "-R" parameter. I explain it here : https://redmine.pfsense.org/issues/10379#note-13

Thanks a lot

**Comment by o71** [comment]
Hi @vktg and @jim-p 

I give you a solution which works here : https://redmine.pfsense.org/issues/10379#note-16

Can you update the pkg ? 

Thanks a lot

**Comment by vktg** [comment]
See https://github.com/pfsense/FreeBSD-ports/pull/814

**Pull request merged**
