### PR TITLE
Add FreeBSD port and pfSense plugin for HoneyTrap #9989

### PR DESCRIPTION
**Pull request by Ezri-Mudde**
This PR adds a FreeBSD port and a pfSense plugin for HoneyTrap.
Ticket #9989

### CODE REVIEW

**Comment by rbgarga** [comment]
We avoid do maintain custom FreeBSD ports as much as we can. You should submit security/honeytrap to FreeBSD before and then use it here on pfSense

**Comment by rbgarga** [comment]
A tickets has been sent to FreeBSD - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232025.

@Ezri-Mudde please re-submit this PR only containing pfSense-pkg-honeytrap port

**Comment by Ezri-Mudde** [comment]
security/honeytrap has been [submitted to](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242740) and [accepted by](https://www.freshports.org/security/honeytrap/) FreeBSD. Should I wait to re-submit the pfSense port until this repo contains the FreeBSD port or re-submit it now?

**Comment by rbgarga** [comment]
@Ezri-Mudde you can send the pfSense port and just add a note that it requires security/honeytrap to be cherry-picked from FreeBSD

**Pull request closed without merging**
