### PR TITLE
Update suricata.inc - fix suricata_Getdirsize tab char

### PR DESCRIPTION
**Pull request by graham-collinson**
Assuming this was intended to be the tab character.  PHP 8 changed strpos so that Integer is no longer cast to a character by strpos.

### CODE REVIEW

**Comment by graham-collinson** [comment]
redmine issue https://redmine.pfsense.org/issues/14855

**Comment by bmeeks8** [comment]
I am good with this fix, but it needs an additional update to the version in the Makefile so that the package will rebuild and show as an available update. Please increment the PORTREVISION parameter in the Makefile to be "2" (it is currently "1" in the DEVEL snapshot branch package). That will make the current Snapshot branch Suricata GUI package version be 7.0.0_2.

**Comment by graham-collinson** [comment]
@bmeeks8 Thanks for the pointer.  That ok now?

**Comment by bmeeks8** [comment]
> @bmeeks8 Thanks for the pointer. That ok now?

Perfect! Now we wait on the Netgate developer team to review and merge. I can drop them an email to hopefully speed it along. They are a bit preoccupied I think with the upcoming 23.09 release.

As the package maintainer, they usually ask me to weigh in with my thoughts on community pull request submissions, so that's why I proactively jumped in.

**Pull request merged**
