### PR TITLE
Correct unblock src/dest IP method call.

### PR DESCRIPTION
**Pull request by renaudholcombe**
This is to correct Bug #7578 (unblock links do not unblock on suricata alerts page).

Bug for reference: https://redmine.pfsense.org/issues/7578

### CODE REVIEW

**Comment by rbgarga** [comment]
Can you check this out please @bmeeks8 ?

**Comment by bmeeks8** [comment]
The suggested fix is good.  Thank you @renaudholcombe for the submission.
Bill Meeks

**Comment by rbgarga** [comment]
Note: Merge combined with #380

**Comment by renaudholcombe** [comment]
Please apply this pull request (#370) before #379.

**Pull request merged**
