### PR TITLE
Move from nut-2.8.0 to nut-devel

### PR DESCRIPTION
**Pull request by dennypage**
Replacement for PR #1295

### CODE REVIEW

**Comment by marcos-ng** [comment]
Unfortunately the build failed again (unclear why at the moment), hence the changes have been reverted.

**Comment by dennypage** [comment]
Are there differences between the NG build environment and the standard FreeBSD environments?

Is it possible for someone outside of NG to replicate the NG build environment?

**Comment by dennypage** [comment]
I have found the issue and understand why pfSense-pkg-nut is not building with nut-devel. A change is required for the nut-devel packing list, which I will submit upstream shortly.

No changes will be required in the pfSense-pkg-nut PR. Is it possible to re-open the PR?

**Comment by marcos-ng** [comment]
This one's already merged, so a new one will be needed (make sure to include `Implement #14795` in the title/commit message).

**Pull request merged**
