### PR TITLE
Fix 404 error to firewall_virtual_ip.php in doco Ticket #13098

### PR DESCRIPTION
**Pull request by c-gunther**
The current pfsense haproxy 0.61_5 package generates a 404 when clicking on the Virtual IP link.
It links to /haproxy/firewall_virtual_ip.php instead of /firewall_virtual_ip.php as the link is relative to the /haproxy sub-directory.
This makes it look as if the haproxy project is meant to ship with a firewall_virtual_ip.php page, instead of linking to the standard pfsense one under Firewall / Virtual IPs.

### CODE REVIEW

**Review by jim-p — CHANGES_REQUESTED** [review]
As a part of this pull request, you must increase PORTVERSION or add a PORTREVISION line in the package Makefile. Without this version increase, the package will not be rebuilt to include the new change.

See https://docs.netgate.com/pfsense/en/latest/references/developer-style-guide.html#ports-packages-specific-rules

**Comment by jim-p** [comment]
To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://docs.netgate.com/pfsense/en/latest/development/pull-request.html
Thanks!

**Comment by c-gunther** [comment]
Redmine link: https://redmine.pfsense.org/issues/13098

Also this page https://docs.netgate.com/pfsense/en/latest/development/pull-request.html says work off master. I think that needs to be updated to say 'devel'.

**Comment by jim-p** [comment]
> Also this page https://docs.netgate.com/pfsense/en/latest/development/pull-request.html says work off master. I think that needs to be updated to say 'devel'.

It says that already. The page text is "Always work on the master branch of the pfSense/pfSense repository or the devel branch of pfSense/FreeBSD-ports" and this is the FreeBSD-ports repository.

**Review by jim-p — APPROVED** [review]

**Pull request merged**
