### PR TITLE
fix typos: unkown -> unknown

### PR DESCRIPTION
**Pull request by stensonb**

### CODE REVIEW

**Comment by jim-p** [comment]
As a part of this pull request, you must increase PORTVERSION or add a PORTREVISION line in the  Makefile for each package that was touched. Without this version increase, the packages will not be rebuilt to include the new change.

See https://www.netgate.com/docs/pfsense/development/developer-style-guide.html#ports-packages-specific-rules

**Comment by stensonb** [comment]
portversion bumped, and squashed into the same commit.

thanks for the pointer!  i look forward to more commits. :)

**Comment by stensonb** [comment]
sigh...reading helps.

bumped/added PORTREVISION, not PORTVERSION.

**Comment by stensonb** [comment]
> Missing version bump(s)

@jim-p should be good now.

**Comment by jim-p** [comment]
Github issue link: https://redmine.pfsense.org/issues/9339

**Comment by rbgarga** [comment]
Manually merged. Thanks!

**Pull request closed without merging**
