### PR TITLE
Status Monitoring - Auto Updating

### PR DESCRIPTION
**Pull request by NOYB**
Auto update graph 4 times per the selected resolution period.
Auto update graph on settings change.

### CODE REVIEW

**Comment by jdillard** [comment]
I like the idea of the auto update, but I think it should be a setting that is off by default and has the options of updating every 1, 5, or 10 minutes. There is no point in updating less than once a minute since the RRD data is polled once a minute.

**Comment by NOYB** [comment]
Agree with it being user enabled option.

Rational for updating 4 times per selected resolution is that the graph updating and RRD updating are not synchronized.  Thus the graph updating is kept from lagging the RRD updates by no more than 1/4th the selected resolution.

**Comment by jdillard** [comment]
I wouldn't over engineer it, RRD isn't really meant for real time stats. I am tempted to change the name back to RRD Graphs from Monitoring as it might be a little misleading on functionality.

**Comment by NOYB** [comment]
If a decision is made not to use “Monitoring” how about one of these?
Status / System Charts
Status / System Graphs
Status / System Health
With or without “System”.
I like Graphs or System Graphs best.  Never did like “RRD Graphs”.  RRD is techie term only known by those who know what it is.

**Comment by jdillard** [comment]
I think just Graphs might be best. RRD does sounds technical. System is one of the categories of graphs, so System Graphs doesn't sound all encompassing, and Status > Status Graphs sounds repetitive.

Ever Knowing (but not understanding) Graphs :)

**Comment by NOYB** [comment]
Replaced by PR #83

**Pull request closed without merging**
