### PR TITLE
Make the HAproxy widget settings panel open

### PR DESCRIPTION
**Pull request by phil-davis**
The id for the settings panel-footer changed its format a bit to support multiple copies of a widget on the dashboard.

### CODE REVIEW

**Comment by phil-davis** [comment]
See redmine issue https://redmine.pfsense.org/issues/7523

**Comment by phil-davis** [comment]
Note: This change goes with pfSense 2.4 and later. It is not for use on 2.3.* systems.

**Comment by rbgarga** [comment]
@phil-davis just to make it easier to maintain, can you do a change that check pfSense version and work both on 2.3 and 2.4?

**Comment by phil-davis** [comment]
@rbgarga I discovered that even better is to just use the $widgetname var, which I had already made upwardly compatible with the dashboard changes in 2.4
See #352

**Pull request closed without merging**
