### PR TITLE
[#4542] Add mpd5 support for the RFC 4638 PPP-Max-Payload tag

### PR DESCRIPTION
**Pull request by davidjwood**
[Redmine #4542](https://redmine.pfsense.org/issues/4542)

Here is the mpd5 patch to support [RFC 4638](https://tools.ietf.org/html/rfc4638), allowing PPPoE to work with an MTU above 1492 on a jumbo capable interface. The history of this patch can be found in [mpd5 bug 54](https://sourceforge.net/p/mpd/bugs/54/#14d2). It has been submitted upstream as [FreeBSD PR 203695](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203695).

The necessary kernel changes were added to HEAD in [r287654](https://svnweb.freebsd.org/base?view=revision&revision=287654), MFCed to stable/10 in [r288918](https://svnweb.freebsd.org/base?view=revision&revision=288918) and incorporated into the devel branch of the pfsense/FreeBSD-src repository by pfsense/FreeBSD-src@945ed01c4bae06169f63978e43029c04d4abd731.

I have installed an mpd5 binary with these changes incorporated into a 2.2.4-RELEASE box with a suitably patched kernel and [tested it successfully](https://forum.pfsense.org/index.php?topic=93902.msg556575#msg556575).

A pull request for the changes to pfsense/pfsense will be submitted shortly.

**Obsoletes:** ~~pull request pfsense/pfsense-tools#12~~ following the decision this feature does not qualify for the feature-frozen RELENG_2_2 branch of pfSense.

**Acknowledgement to:** Dmitry Luhtionov (mpd developer), who is responsible for the underlying work.

### CODE REVIEW

**Comment by davidjwood** [comment]
Work in progress on the pfSense support can be found in the [rfc4638 branch of davidjwood/pfsense](https://github.com/davidjwood/pfsense/tree/rfc4638).

**Comment by davidjwood** [comment]
The pfSense support is completed, tested and found in pfsense/pfsense#1959.

**Comment by davidjwood** [comment]
@loos-br I understand the Redmine bug is allocated to you.

**Comment by rbgarga** [comment]
@davidjwood why do you think about adding these changes into FreeBSD ports tree? It could be an extra patch, optional, and check for FreeBSD OSVERSION to make sure it has the kernel changes

It would make sense since more FreeBSD users could bennefit of this change.

If you are interested, I can help you to get it committed there since I'm a FreeBSD ports committer, we would only need to get an approval from port maintainer

**Comment by rbgarga** [comment]
@davidjwood nevermind, I'll make the changes on FreeBSD ports and also merge this one here.

Thanks!!!

**Comment by davidjwood** [comment]
@rbgarga Thanks for the merge.

I'd already submitted the patch upstream in [FreeBSD PR 203695](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203695) and notice you've added yourself to the cc list on that PR. Hopefully it gets incorporated into the ports tree sometime soon.

**Pull request merged**
