### PR TITLE
bind package pfSense 2.3

### PR DESCRIPTION
**Pull request by svenauhagen**
Initial commit bind package

@cbuechler sure, no problem.
Here is a fresh commit.

Thanks

### CODE REVIEW

**Comment by klepallec** [comment]
Hi, 

I'm really interessing about this package.
Do you know a realease date ?

thanks

**Comment by cbuechler** [comment]
Merged, thanks @svenauhagen ! 

Should show up in the next hour or so.

**Comment by rbgarga** [comment]
@svenauhagen I didn't understand why you needed to create that port bind-pfsense. What is the idea behind it?

**Comment by svenauhagen** [comment]
Hi,

the problem is the pfSense package depends on bind-tools which is in conflict with bind.
bind-tools is just a meta package containing a subset of files from the bind package.

So we created a package bind-pfsense containing the files from bind excluding the files already in bind-tools so the entire bind package files are installed.

I hope that makes it more understandable.

Best
Sven

**Pull request merged**
