### PR TITLE
Status / monitoring   graph types

### PR DESCRIPTION
**Pull request by NOYB**

### CODE REVIEW

**Comment by jdillard** [comment]
I don't know if those options are ready for primetime just yet. The bar graphs make it look kind of cool though :)

**Comment by NOYB** [comment]
> I don't know if those options are ready for primetime just yet.
What is the issue?

**Comment by jdillard** [comment]
I don't think bars are appropriate for this type of graph and area had some weird issues when I toggled some labels on an inverted graph.

**Comment by NOYB** [comment]
Why not let the user decide if bars are appropriate for them and what they want to get from the graph?

**Comment by gonzopancho** [comment]
ping @jdillard let's get to some resolution on this.

**Pull request merged**
