### PR TITLE
Dashboard widget for Traffic Totals

### PR DESCRIPTION
**Pull request by SunStroke74**
Shows today's and this month in/out traffic totals for each of interfaces.
Please check makefile changes as I don't have many expierience in it.

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by doktornotor** [comment]
@SunStroke74 - fixed the licenses with https://github.com/SunStroke74/FreeBSD-ports/pull/1

@jdillard @rbgarga - can someone check this? Been sitting here for a while.

**Comment by rbgarga** [comment]
Oh, and now I noted it was submitted against RELENG_2_3_2, which is a maintenance branch. @SunStroke74 please re-submit against master or at least RELENG_2_3

**Comment by rbgarga** [comment]
Please re-submit against devel branch

**Pull request closed without merging**
