### PR TITLE
Suricata GID:SID rule pop-up. Feature #12297

### PR DESCRIPTION
**Pull request by vktg**
- [X] Redmine Issue: https://redmine.pfsense.org/issues/12297
- [X] Ready for review

can be merged with https://github.com/pfsense/FreeBSD-ports/pull/1097

### CODE REVIEW

**Comment by bmeeks8** [comment]
Another great addition to the GUI. Thanks Viktor!

**Comment by rbgarga** [comment]
@vktg please rebase your fork and fix conflicts

**Comment by vktg** [comment]
Rebased

**Comment by vktg** [comment]
+ version bump

**Pull request merged**
