### PR TITLE
adding extended custom http eve.json fields

### PR DESCRIPTION
**Pull request by fgrosswig**
why not adding this fields to the custom fields? maybe needs a suboption at the interface or could stay as it is to extend the http eve.json information as default.

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by rbgarga** [comment]
@bmeeks8 can you check this out, please?

**Comment by fgrosswig** [comment]
well, signed it ... whats next?

**Comment by rbgarga** [comment]
We just need to wait for @bmeeks8 to take a look at it too

**Comment by bmeeks8** [comment]
I am fine with this addition.  It will make the EVE output logging in Suricata better.  Thank you to @fgrosswig for the submission!

Bill

**Comment by securitym0nkey** [comment]
I know i'm late to the game as this is already merged. But i think that are too many fields to be logged as default just by enabling extended http log. It might put unneeded load the log/even storage. For example an ELK stack where elastic would index all those fields. @fgrosswig would you be happy if we had an option to define the fields one is interested in via the gui? To have more granular control over the eve-output is something i'm working on anyway. You can have a look [here](https://github.com/securitym0nkey/FreeBSD-ports/tree/suricata-granular-eve-output-settings)

**Comment by fgrosswig** [comment]
@securitym0nkey: first i would say what people going to store on elk will do with the "extend" logg option anyway extended infos. So why limiting it not takeing advantage of the built in "extended" options in exact this case. I was wondering why "extended" logging to http does not have the whole set. And second, as mentioned above, it would be a best thing to have a textfield or multiple choice to exactly choose what specific option you are going to store on elk. But this is the higher class and would need some additional tweaks on the interface i was too lazy to take also care of - beause as said: if i check amr extended then i expect the "whole" extended and not limitin extended output.

**Pull request merged**
