### PR TITLE
Fix missing portscan UDP protocol and fix typos

### PR DESCRIPTION
**Pull request by Andrew17856**
Dealing with the issues in https://redmine.pfsense.org/issues/6356

1)  Missing UDP protocol in the port scan settings
2)  Various typos

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by Andrew17856** [comment]
I signed and returned the CLA on 22 April 2016 by email.  Please can you check and confirm.

**Comment by Andrew17856** [comment]
Have sent it to you again just now for good measure.

**Comment by Andrew17856** [comment]
... and have signed it electronically on the pfSense portal.

**Comment by bmeeks8** [comment]
I'm OK with these updates to Snort and thanks again Andew for the contribution.

Bill

**Comment by Andrew17856** [comment]
Thanks Bill. My pleasure.

**Comment by bmeeks8** [comment]
I incorporated the fixes in this Pull Request into the last Snort GUI package update (version 3.2.9.1_14), so this request can be closed.

**Pull request closed without merging**
